package com.numhero.shared.service;

import com.google.gwt.user.client.rpc.IsSerializable;

public enum ApplicationCommandEnum implements IsSerializable {
    CommandLogin,
    CommandGetBusinessAccount, CommandSaveBusinessAccount,
    CommandGetBankAccount, CommandSaveBankAccount,
    CommandGetClientSupplier, CommandGetClients,
    CommandGetReceipt, CommandSaveReceipt,
    CommandGetInvoice, CommandGetInvoices, CommandSaveInvoice,
    CommandGetProduct, CommandSaveProduct,
    CommandGetTaxInfo, CommandSaveTaxInfo, CommandGetTaxInfos,
    CommandGetUser, CommandSaveUser,
    CommandGetProject, CommandSaveProject,
    CommandGetTask, CommandSaveTask,
    CommandGetTimeEntry, CommandSaveTimeEntry,
    CommandGetSettings, CommandSaveSettings,
    CommandGetBankAccounts, CommandGetReceipts,
    CommandGetProductServices,
    CommandGetTasks,
    CommandGetProjects, CommandGetTimeEntries,
    CommandGetStaffMember,
    CommandGetSuppliers,
    CommandSaveClientSupplier, CommandSaveStaff, CommandGetStaffMembers, CommandDeleteClientsSuppliers,
    CommandDeleteBankAccounts, CommandDeleteReceipts,
    CommandDeleteDocuments, CommandDeleteProducts, CommandDeleteProjects, CommandProjectGenerateInvoice,
    CommandDeleteTasks, CommandDeleteStaff, CommandDeleteTimeEntries,
    CommandGetUsers, CommandDeleteUsers, CommandSuspendUsers, CommandReactivateUsers,
    CommandConvertToInvoices,
    CommandChangeStatusOfDocuments,
    CommandProjectsRaiseEstimates,
    CommandStaffProjectsListRequest, CommandProjectTasksListRequest, CommandGetBillableTimeEntries,
    CommandTimeEntriesBilledStatus,
    CommandGetCategories, CommandDeleteCategories, CommandGetCategory, CommandSaveCategory, CommandReceiptsBilledStatus,
    CommandGetBillableReceipts,
    CommandSendInvoiceByMail,
    CommandSaveBankTransaction, CommandDeleteBankTransactions, CommandGetBankTransactions,
    CommandGetBankTransaction, CommandGetProfitLoss, CommandPaidReceipts, CommandGetCurrencyConversion,
    CommandGetUnbilledReceipt, CommandGetUnpaidReceipts, CommandGetChartOfAccounts, CommandGetAccounts,
    CommandGetBusinessTransactions, CommandGetBusinessTransaction, CommandGetExpenseAccounts,
    CommandGetTrialBalance, CommandHomeRecap, CommandMoneyRecap, CommandDeleteTaxInfos, CommandGetAccountBalance, CommandGetDeposits, CommandGetReceivables, CommandGetTaxes, CommandGetVAT, CommandGetMoneyInRecap, CommandGetMoneyOutRecap, CommandMoneyOutRecap, CommandGetReimbursableStaffMembers, CommandDirectPaymentStaffMembers, CommandGetMainTradingBankAccount, CommandSaveUserMessage, CommandSaveReportBug, CommandChangeSupplierStatusOfDocuments, CommandGetBusinessTransactionLegs,
    CommandGlobalSearch;
}
